# Generated by Django 3.0 on 2020-01-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial_emp_migration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee',
        ),
    ]
