# Generated by Django 3.0.2 on 2020-01-12 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200112_1618'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employer',
            table='employer',
        ),
    ]
