# Generated by Django 2.2.5 on 2019-12-26 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='person',
            name='url',
            field=models.URLField(default='', verbose_name='url'),
        ),
    ]
